name: Build Android APK

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      APK_PATH: android/app/build/outputs/apk/debug/gmboy-android-universal.apk
      APK_BUILD_PATH: android/app/build/outputs/apk/debug/app-debug.apk
      APK_NAME: gmboy-android-universal.apk

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          ndk: 26.3.11579264
          cmake: 3.22.1

      - name: Build Rust libraries
        working-directory: ./android
        run: |
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/26.3.11579264
          ./build.sh

      - name: Build APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv "$APK_BUILD_PATH" "$APK_PATH"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
